"""
Django settings for nebula project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s@+z#(rz)oc)!&(=j@3!5#q)l&t(w9f+33p&9^q2e7clg^31jz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'corsheaders',
    'learning',
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nebula.urls'
DEFAULT_CHARSET = 'utf-8'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nebula.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'frontend' / 'dist']

# SimpleUI
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menus': [
        {
            'name': '考试管理',
            'icon': 'fas fa-graduation-cap',
            'models': [
                {'name': '考试', 'icon': 'fas fa-file-excel', 'url': '/admin/learning/exam/'},
                {'name': '试题', 'icon': 'fas fa-question-circle', 'url': '/admin/learning/question/'},
                {'name': '考试成绩', 'icon': 'fas fa-history', 'url': '/admin/learning/examresult/'}
            ]
        }, {
            'name': '称号管理',
            'icon': 'fas fa-award',
            'models': [
                {'name': '称号', 'icon': 'fas fa-star', 'url': '/admin/learning/badge/'},
                {'name': '学员称号', 'icon': 'fas fa-user-graduate', 'url': '/admin/learning/userbadge/'}
            ]
        }, {
            'appid': 'learning',
            'name': '反馈与公告',
            'icon': 'fas fa-bullhorn',
            'models': [
                {'name': '反馈记录', 'icon': 'fas fa-comment-dots', 'url': '/admin/learning/study/'},
                {'name': '系统公告', 'icon': 'fas fa-bell', 'url': '/admin/learning/announcement/'}
            ]
        }, {
            'name': '培训闯关管理',
            'icon': 'fas fa-flag-checkered',
            'models': [
                {'name': '培训项目', 'icon': 'fas fa-project-diagram', 'url': '/admin/learning/trainingprogram/'},
                {'name': '闯关节点', 'icon': 'fas fa-tasks', 'url': '/admin/learning/checkpointnode/'},
                {'name': '员工闯关进度', 'icon': 'fas fa-chart-line', 'url': '/admin/learning/employeecheckpoint/'}
            ]
        }, {
            'name': '员工管理',
            'icon': 'fas fa-id-card',
            'models': [
                {'name': '员工列表', 'icon': 'fas fa-address-book', 'url': '/admin/learning/employee/'},
                {'name': '员工培训记录', 'icon': 'fas fa-users', 'url': '/admin/learning/employeeprogram/'}
            ]
        }
    ]
}



# ---- Railway / Production ----
import os
import dj_database_url

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', SECRET_KEY)
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://*.up.railway.app,https://*.loca.lt,https://*.github.io').split(',')

# Use Railway PostgreSQL when DATABASE_URL is set
# Create .use_pg file in project root to also use PostgreSQL locally (sync)
DATABASE_URL = os.environ.get('DATABASE_URL')
if not DATABASE_URL and os.path.exists(BASE_DIR / '.use_pg'):
    DATABASE_URL = 'postgresql://postgres:unwNTHjOZeDQjzpoLMPFVQloJBDGURej@reseau.proxy.rlwy.net:15960/railway'
if DATABASE_URL:
    DATABASES['default'] = dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
    )

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Static files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'frontend' / 'dist',
    BASE_DIR / 'star_course',
]

# Fix template dirs for deployment
TEMPLATES[0]['DIRS'] = [
    BASE_DIR / 'frontend' / 'dist',
    BASE_DIR / 'star_course',
]

# Whitenoise for production static files
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

