/** 十五五 · 星途大冒险 - 30个任务代号 */
const MISSION_CODENAMES = [
  { code: "M-01", name: "星火燎原", icon: "🔥", ep: "星火篇 · 点燃十五五" },
  { code: "M-02", name: "征途号角", icon: "📯", ep: "星火篇 · 点燃十五五" },
  { code: "M-03", name: "砺剑出鞘", icon: "⚔️", ep: "星火篇 · 点燃十五五" },
  { code: "M-04", name: "品质坚守", icon: "🛡️", ep: "星火篇 · 点燃十五五" },
  { code: "M-05", name: "首战告捷", icon: "🏁", ep: "星火篇 · 点燃十五五" },
  { code: "M-06", name: "以心换心", icon: "💎", ep: "破冰篇 · 服务深耕" },
  { code: "M-07", name: "标准之战", icon: "📋", ep: "破冰篇 · 服务深耕" },
  { code: "M-08", name: "危机营救", icon: "🚨", ep: "破冰篇 · 服务深耕" },
  { code: "M-09", name: "设备保卫战", icon: "🔧", ep: "破冰篇 · 服务深耕" },
  { code: "M-10", name: "安全防线", icon: "🔒", ep: "破冰篇 · 服务深耕" },
  { code: "M-11", name: "智慧启航", icon: "⚡", ep: "智慧篇 · 科技赋能" },
  { code: "M-12", name: "万物互联", icon: "🌐", ep: "智慧篇 · 科技赋能" },
  { code: "M-13", name: "数据迷城", icon: "📊", ep: "智慧篇 · 科技赋能" },
  { code: "M-14", name: "未来触点", icon: "🖐️", ep: "智慧篇 · 科技赋能" },
  { code: "M-15", name: "创新突围", icon: "💡", ep: "智慧篇 · 科技赋能" },
  { code: "M-16", name: "客户心连心", icon: "❤️", ep: "超越篇 · 品质升华" },
  { code: "M-17", name: "品质狙击", icon: "🎯", ep: "超越篇 · 品质升华" },
  { code: "M-18", name: "社区嘉年华", icon: "🎪", ep: "超越篇 · 品质升华" },
  { code: "M-19", name: "沟通兵法", icon: "📢", ep: "超越篇 · 品质升华" },
  { code: "M-20", name: "巅峰对决", icon: "🏆", ep: "超越篇 · 品质升华" },
  { code: "M-21", name: "目标狩猎", icon: "🎯", ep: "将帅篇 · 管理砺剑" },
  { code: "M-22", name: "团队集结", icon: "🤝", ep: "将帅篇 · 管理砺剑" },
  { code: "M-23", name: "时间突围", icon: "⏰", ep: "将帅篇 · 管理砺剑" },
  { code: "M-24", name: "授权兵法", icon: "📜", ep: "将帅篇 · 管理砺剑" },
  { code: "M-25", name: "绩效之战", icon: "📈", ep: "将帅篇 · 管理砺剑" },
  { code: "M-26", name: "行业洞察", icon: "🔭", ep: "决胜篇 · 未来已来" },
  { code: "M-27", name: "绿色使命", icon: "🌿", ep: "决胜篇 · 未来已来" },
  { code: "M-28", name: "应急突击", icon: "🚁", ep: "决胜篇 · 未来已来" },
  { code: "M-29", name: "标杆对决", icon: "⚖️", ep: "决胜篇 · 未来已来" },
  { code: "M-30", name: "终极荣耀", icon: "👑", ep: "决胜篇 · 未来已来" }
];