# Generated by Django 6.0.6 on 2026-06-22 08:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('date', models.DateField(verbose_name='发布日期')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统公告',
                'verbose_name_plural': '系统公告',
                'db_table': 'announcement',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='称号名称')),
                ('description', models.TextField(verbose_name='获取条件')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标标识')),
            ],
            options={
                'verbose_name': '称号',
                'verbose_name_plural': '称号管理',
                'db_table': 'badge',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CheckpointNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('checkin', '签到'), ('assessment', '评估'), ('exam', '考试')], max_length=20, verbose_name='类型')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'checkpoint_node',
                'ordering': ['program', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='工号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='所属公司')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='岗位')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('hired_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='考试标题')),
                ('description', models.TextField(blank=True, verbose_name='考试说明')),
                ('passing_score', models.IntegerField(default=60, verbose_name='及格分数')),
                ('max_attempts', models.IntegerField(default=3, verbose_name='最大考试次数')),
                ('slug', models.CharField(default=uuid.uuid4, editable=False, max_length=32, unique=True, verbose_name='分享链接标识')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间')),
                ('target_areas', models.CharField(blank=True, max_length=500, verbose_name='推送区域')),
                ('is_published', models.BooleanField(default=False, verbose_name='已发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试管理',
                'db_table': 'exam',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('company', models.CharField(max_length=100, verbose_name='所属公司')),
                ('department', models.CharField(blank=True, default='', max_length=100, verbose_name='部门')),
                ('position', models.CharField(max_length=50, verbose_name='岗位')),
                ('wechat', models.CharField(blank=True, max_length=100, verbose_name='联系方式')),
                ('description', models.TextField(verbose_name='问题/需求描述')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '反馈记录',
                'verbose_name_plural': '反馈记录',
                'db_table': 'study',
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '培训项目',
                'verbose_name_plural': '培训项目',
                'db_table': 'training_program',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', '未解锁'), ('current', '当前关卡'), ('completed', '已完成')], default='locked', max_length=20, verbose_name='状态')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_progress', to='learning.employee')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_progress', to='learning.checkpointnode')),
            ],
            options={
                'db_table': 'employee_checkpoint',
            },
        ),
        migrations.AddField(
            model_name='checkpointnode',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.exam'),
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='学员姓名')),
                ('user_area', models.CharField(blank=True, max_length=100, verbose_name='所属分公司')),
                ('employee_id', models.CharField(blank=True, default='', max_length=50, verbose_name='工号')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='手机号')),
                ('company', models.CharField(blank=True, default='', max_length=100, verbose_name='归属公司')),
                ('department', models.CharField(blank=True, default='', max_length=100, verbose_name='部门')),
                ('score', models.IntegerField(verbose_name='得分')),
                ('total_score', models.IntegerField(verbose_name='总分')),
                ('is_passed', models.BooleanField(verbose_name='是否及格')),
                ('attempt_num', models.IntegerField(default=1, verbose_name='考试次数')),
                ('answers', models.TextField(blank=True, verbose_name='答题详情')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.exam', verbose_name='考试')),
            ],
            options={
                'verbose_name': '考试成绩',
                'verbose_name_plural': '考试成绩',
                'db_table': 'exam_result',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single', '单选题'), ('multi', '多选题'), ('judge', '判断题')], default='single', max_length=10, verbose_name='题型')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('option_a', models.CharField(blank=True, max_length=300)),
                ('option_b', models.CharField(blank=True, max_length=300)),
                ('option_c', models.CharField(blank=True, max_length=300)),
                ('option_d', models.CharField(blank=True, max_length=300)),
                ('answer', models.CharField(max_length=10, verbose_name='正确答案')),
                ('score', models.IntegerField(default=2, verbose_name='分值')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.exam', verbose_name='所属考试')),
            ],
            options={
                'verbose_name': '试题',
                'verbose_name_plural': '试题管理',
                'db_table': 'question',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '未开始'), ('in_progress', '进行中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='learning.employee')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='learning.trainingprogram')),
            ],
            options={
                'db_table': 'employee_program',
            },
        ),
        migrations.AddField(
            model_name='checkpointnode',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='learning.trainingprogram'),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='学员姓名')),
                ('user_area', models.CharField(blank=True, max_length=100, verbose_name='所属分公司')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='获取时间')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.badge', verbose_name='称号')),
            ],
            options={
                'verbose_name': '学员称号',
                'verbose_name_plural': '学员称号',
                'db_table': 'user_badge',
                'ordering': ['-earned_at'],
            },
        ),
    ]
