# Generated by Django 6.0.6 on 2026-06-22 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkpointnode',
            options={'ordering': ['program', 'order'], 'verbose_name': '闯关节点', 'verbose_name_plural': '闯关节点'},
        ),
        migrations.AlterModelOptions(
            name='employeecheckpoint',
            options={'verbose_name': '员工闯关进度', 'verbose_name_plural': '员工闯关进度'},
        ),
        migrations.AlterModelOptions(
            name='employeeprogram',
            options={'verbose_name': '员工培训记录', 'verbose_name_plural': '员工培训记录'},
        ),
        migrations.AlterModelOptions(
            name='trainingprogram',
            options={'ordering': ['-created_at'], 'verbose_name': '培训项目', 'verbose_name_plural': '培训项目'},
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='关联账号'),
        ),
        migrations.AlterField(
            model_name='checkpointnode',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.exam', verbose_name='关联考试'),
        ),
        migrations.AlterField(
            model_name='checkpointnode',
            name='node_type',
            field=models.CharField(choices=[('checkin', '签到'), ('assessment', '评估'), ('exam', '考试')], max_length=20, verbose_name='节点类型'),
        ),
        migrations.AlterField(
            model_name='checkpointnode',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='learning.trainingprogram', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='employeecheckpoint',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_progress', to='learning.employee', verbose_name='员工'),
        ),
        migrations.AlterField(
            model_name='employeecheckpoint',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_progress', to='learning.checkpointnode', verbose_name='节点'),
        ),
        migrations.AlterField(
            model_name='employeeprogram',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='learning.employee', verbose_name='员工'),
        ),
        migrations.AlterField(
            model_name='employeeprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='learning.trainingprogram', verbose_name='培训项目'),
        ),
        migrations.AlterUniqueTogether(
            name='employeecheckpoint',
            unique_together={('employee', 'node')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeprogram',
            unique_together={('employee', 'program')},
        ),
        migrations.CreateModel(
            name='StarDailyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('department', models.CharField(blank=True, default='', max_length=100, verbose_name='部门')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='联系方式')),
                ('checkin_date', models.DateField(auto_now_add=True, verbose_name='打卡日期')),
                ('checkin_time', models.DateTimeField(auto_now_add=True, verbose_name='打卡时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
            ],
            options={
                'verbose_name': '打卡记录',
                'verbose_name_plural': '打卡记录',
                'db_table': 'star_daily_checkin',
                'ordering': ['-checkin_time'],
                'unique_together': {('name', 'checkin_date')},
            },
        ),
        migrations.CreateModel(
            name='StarCheckinScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(verbose_name='天数')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('hp_left', models.IntegerField(default=5, verbose_name='剩余生命')),
                ('answers_json', models.TextField(blank=True, default='', verbose_name='答案JSON')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '闯关成绩',
                'verbose_name_plural': '闯关成绩',
                'db_table': 'star_checkin_score',
                'ordering': ['day_number'],
                'unique_together': {('user', 'day_number')},
            },
        ),
    ]
