# Generated by Django 6.0.6 on 2026-06-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_checkpointnode_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(unique=True, verbose_name='天数')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('knowledge', models.TextField(blank=True, help_text='每行一条简报内容，最多5条', verbose_name='知识简报（每行一条）')),
                ('questions_json', models.TextField(blank=True, help_text='[{"question":"题目","options":["A","B","C","D"],"correctIndex":1}]', verbose_name='题目JSON')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '闯关题目',
                'verbose_name_plural': '闯关题目管理',
                'db_table': 'checkin_content',
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='CheckinMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(unique=True, verbose_name='天数')),
                ('code', models.CharField(default='M-01', max_length=10, verbose_name='代号')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('icon', models.CharField(default='🔥', max_length=10, verbose_name='图标')),
                ('episode', models.CharField(default='星火篇', max_length=50, verbose_name='篇章')),
            ],
            options={
                'verbose_name': '闯关任务',
                'verbose_name_plural': '闯关任务管理',
                'db_table': 'checkin_mission',
                'ordering': ['day_number'],
            },
        ),
    ]
